spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.143.9.57:3306/gym?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: admin
    password: biyesheji

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/

mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  returnPageInfo: check
  params: count=countSql

